//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public Administrador()
        {
            this.Reporte = new HashSet<Reporte>();
            this.ReporteSolucionado = new HashSet<ReporteSolucionado>();
        }
    
        public int idAdministrador { get; set; }
        public string nombre { get; set; }
        public int desuso { get; set; }
        public byte[] foto { get; set; }
        public Nullable<bool> tecnico { get; set; }
    
        public virtual ICollection<Reporte> Reporte { get; set; }
        public virtual ICollection<ReporteSolucionado> ReporteSolucionado { get; set; }
    }
}
