//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public Equipo()
        {
            this.ProblemaPosible = new HashSet<ProblemaPosible>();
            this.Reporte = new HashSet<Reporte>();
            this.ReporteSolucionado = new HashSet<ReporteSolucionado>();
        }
    
        public int idEquipo { get; set; }
        public string nombre { get; set; }
        public int desuso { get; set; }
    
        public virtual ICollection<ProblemaPosible> ProblemaPosible { get; set; }
        public virtual ICollection<Reporte> Reporte { get; set; }
        public virtual ICollection<ReporteSolucionado> ReporteSolucionado { get; set; }
    }
}
