//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_Reporte_Administrador", "Administrador", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ReportesApp.Administrador), "Reporte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.Reporte), true)]
[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_ReporteSolucionado_Administrador", "Administrador", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportesApp.Administrador), "ReporteSolucionado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.ReporteSolucionado), true)]
[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_Reporte_Entorno", "Entorno", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ReportesApp.Entorno), "Reporte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.Reporte), true)]
[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_ReporteSolucionado_Entorno", "Entorno", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ReportesApp.Entorno), "ReporteSolucionado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.ReporteSolucionado), true)]
[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_ProblemaPosible_Equipo1", "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportesApp.Equipo), "ProblemaPosible", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.ProblemaPosible), true)]
[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_Reporte_Equipo", "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportesApp.Equipo), "Reporte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.Reporte), true)]
[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_ReporteSolucionado_Equipo", "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportesApp.Equipo), "ReporteSolucionado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.ReporteSolucionado), true)]
[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_Reporte_ProblemaPosible", "ProblemaPosible", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportesApp.ProblemaPosible), "Reporte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.Reporte), true)]
[assembly: EdmRelationshipAttribute("ReporteDBModel", "FK_ReporteSolucionado_ProblemaPosible", "ProblemaPosible", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportesApp.ProblemaPosible), "ReporteSolucionado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportesApp.ReporteSolucionado), true)]

#endregion

namespace ReportesApp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ReporteDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ReporteDBEntities object using the connection string found in the 'ReporteDBEntities' section of the application configuration file.
        /// </summary>
        public ReporteDBEntities() : base("name=ReporteDBEntities", "ReporteDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReporteDBEntities object.
        /// </summary>
        public ReporteDBEntities(string connectionString) : base(connectionString, "ReporteDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReporteDBEntities object.
        /// </summary>
        public ReporteDBEntities(EntityConnection connection) : base(connection, "ReporteDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Acceso> Acceso
        {
            get
            {
                if ((_Acceso == null))
                {
                    _Acceso = base.CreateObjectSet<Acceso>("Acceso");
                }
                return _Acceso;
            }
        }
        private ObjectSet<Acceso> _Acceso;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Administrador> Administrador
        {
            get
            {
                if ((_Administrador == null))
                {
                    _Administrador = base.CreateObjectSet<Administrador>("Administrador");
                }
                return _Administrador;
            }
        }
        private ObjectSet<Administrador> _Administrador;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Consecutivo> Consecutivo
        {
            get
            {
                if ((_Consecutivo == null))
                {
                    _Consecutivo = base.CreateObjectSet<Consecutivo>("Consecutivo");
                }
                return _Consecutivo;
            }
        }
        private ObjectSet<Consecutivo> _Consecutivo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Entorno> Entorno
        {
            get
            {
                if ((_Entorno == null))
                {
                    _Entorno = base.CreateObjectSet<Entorno>("Entorno");
                }
                return _Entorno;
            }
        }
        private ObjectSet<Entorno> _Entorno;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Equipo> Equipo
        {
            get
            {
                if ((_Equipo == null))
                {
                    _Equipo = base.CreateObjectSet<Equipo>("Equipo");
                }
                return _Equipo;
            }
        }
        private ObjectSet<Equipo> _Equipo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProblemaPosible> ProblemaPosible
        {
            get
            {
                if ((_ProblemaPosible == null))
                {
                    _ProblemaPosible = base.CreateObjectSet<ProblemaPosible>("ProblemaPosible");
                }
                return _ProblemaPosible;
            }
        }
        private ObjectSet<ProblemaPosible> _ProblemaPosible;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reporte> Reporte
        {
            get
            {
                if ((_Reporte == null))
                {
                    _Reporte = base.CreateObjectSet<Reporte>("Reporte");
                }
                return _Reporte;
            }
        }
        private ObjectSet<Reporte> _Reporte;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReporteSolucionado> ReporteSolucionado
        {
            get
            {
                if ((_ReporteSolucionado == null))
                {
                    _ReporteSolucionado = base.CreateObjectSet<ReporteSolucionado>("ReporteSolucionado");
                }
                return _ReporteSolucionado;
            }
        }
        private ObjectSet<ReporteSolucionado> _ReporteSolucionado;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Acceso EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAcceso(Acceso acceso)
        {
            base.AddObject("Acceso", acceso);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Administrador EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdministrador(Administrador administrador)
        {
            base.AddObject("Administrador", administrador);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Consecutivo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsecutivo(Consecutivo consecutivo)
        {
            base.AddObject("Consecutivo", consecutivo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Entorno EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntorno(Entorno entorno)
        {
            base.AddObject("Entorno", entorno);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Equipo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEquipo(Equipo equipo)
        {
            base.AddObject("Equipo", equipo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProblemaPosible EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProblemaPosible(ProblemaPosible problemaPosible)
        {
            base.AddObject("ProblemaPosible", problemaPosible);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reporte EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReporte(Reporte reporte)
        {
            base.AddObject("Reporte", reporte);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReporteSolucionado EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReporteSolucionado(ReporteSolucionado reporteSolucionado)
        {
            base.AddObject("ReporteSolucionado", reporteSolucionado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="Acceso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Acceso : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Acceso object.
        /// </summary>
        /// <param name="idAcceso">Initial value of the idAcceso property.</param>
        /// <param name="pass">Initial value of the pass property.</param>
        public static Acceso CreateAcceso(global::System.Int32 idAcceso, global::System.String pass)
        {
            Acceso acceso = new Acceso();
            acceso.idAcceso = idAcceso;
            acceso.pass = pass;
            return acceso;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAcceso
        {
            get
            {
                return _idAcceso;
            }
            set
            {
                if (_idAcceso != value)
                {
                    OnidAccesoChanging(value);
                    ReportPropertyChanging("idAcceso");
                    _idAcceso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idAcceso");
                    OnidAccesoChanged();
                }
            }
        }
        private global::System.Int32 _idAcceso;
        partial void OnidAccesoChanging(global::System.Int32 value);
        partial void OnidAccesoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pass
        {
            get
            {
                return _pass;
            }
            set
            {
                OnpassChanging(value);
                ReportPropertyChanging("pass");
                _pass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pass");
                OnpassChanged();
            }
        }
        private global::System.String _pass;
        partial void OnpassChanging(global::System.String value);
        partial void OnpassChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="Administrador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Administrador : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Administrador object.
        /// </summary>
        /// <param name="idAdministrador">Initial value of the idAdministrador property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="desuso">Initial value of the desuso property.</param>
        public static Administrador CreateAdministrador(global::System.Int32 idAdministrador, global::System.String nombre, global::System.Int32 desuso)
        {
            Administrador administrador = new Administrador();
            administrador.idAdministrador = idAdministrador;
            administrador.nombre = nombre;
            administrador.desuso = desuso;
            return administrador;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAdministrador
        {
            get
            {
                return _idAdministrador;
            }
            set
            {
                if (_idAdministrador != value)
                {
                    OnidAdministradorChanging(value);
                    ReportPropertyChanging("idAdministrador");
                    _idAdministrador = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idAdministrador");
                    OnidAdministradorChanged();
                }
            }
        }
        private global::System.Int32 _idAdministrador;
        partial void OnidAdministradorChanging(global::System.Int32 value);
        partial void OnidAdministradorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 desuso
        {
            get
            {
                return _desuso;
            }
            set
            {
                OndesusoChanging(value);
                ReportPropertyChanging("desuso");
                _desuso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("desuso");
                OndesusoChanged();
            }
        }
        private global::System.Int32 _desuso;
        partial void OndesusoChanging(global::System.Int32 value);
        partial void OndesusoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] foto
        {
            get
            {
                return StructuralObject.GetValidValue(_foto);
            }
            set
            {
                OnfotoChanging(value);
                ReportPropertyChanging("foto");
                _foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("foto");
                OnfotoChanged();
            }
        }
        private global::System.Byte[] _foto;
        partial void OnfotoChanging(global::System.Byte[] value);
        partial void OnfotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> tecnico
        {
            get
            {
                return _tecnico;
            }
            set
            {
                OntecnicoChanging(value);
                ReportPropertyChanging("tecnico");
                _tecnico = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tecnico");
                OntecnicoChanged();
            }
        }
        private Nullable<global::System.Boolean> _tecnico;
        partial void OntecnicoChanging(Nullable<global::System.Boolean> value);
        partial void OntecnicoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_Reporte_Administrador", "Reporte")]
        public EntityCollection<Reporte> Reporte
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reporte>("ReporteDBModel.FK_Reporte_Administrador", "Reporte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reporte>("ReporteDBModel.FK_Reporte_Administrador", "Reporte", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ReporteSolucionado_Administrador", "ReporteSolucionado")]
        public EntityCollection<ReporteSolucionado> ReporteSolucionado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReporteSolucionado>("ReporteDBModel.FK_ReporteSolucionado_Administrador", "ReporteSolucionado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReporteSolucionado>("ReporteDBModel.FK_ReporteSolucionado_Administrador", "ReporteSolucionado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="Consecutivo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Consecutivo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Consecutivo object.
        /// </summary>
        /// <param name="idConsecutivo">Initial value of the idConsecutivo property.</param>
        /// <param name="consecutivoSecuencia">Initial value of the consecutivoSecuencia property.</param>
        public static Consecutivo CreateConsecutivo(global::System.Int32 idConsecutivo, global::System.Int32 consecutivoSecuencia)
        {
            Consecutivo consecutivo = new Consecutivo();
            consecutivo.idConsecutivo = idConsecutivo;
            consecutivo.consecutivoSecuencia = consecutivoSecuencia;
            return consecutivo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idConsecutivo
        {
            get
            {
                return _idConsecutivo;
            }
            set
            {
                if (_idConsecutivo != value)
                {
                    OnidConsecutivoChanging(value);
                    ReportPropertyChanging("idConsecutivo");
                    _idConsecutivo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idConsecutivo");
                    OnidConsecutivoChanged();
                }
            }
        }
        private global::System.Int32 _idConsecutivo;
        partial void OnidConsecutivoChanging(global::System.Int32 value);
        partial void OnidConsecutivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 consecutivoSecuencia
        {
            get
            {
                return _consecutivoSecuencia;
            }
            set
            {
                OnconsecutivoSecuenciaChanging(value);
                ReportPropertyChanging("consecutivoSecuencia");
                _consecutivoSecuencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("consecutivoSecuencia");
                OnconsecutivoSecuenciaChanged();
            }
        }
        private global::System.Int32 _consecutivoSecuencia;
        partial void OnconsecutivoSecuenciaChanging(global::System.Int32 value);
        partial void OnconsecutivoSecuenciaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="Entorno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Entorno : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Entorno object.
        /// </summary>
        /// <param name="idEntorno">Initial value of the idEntorno property.</param>
        /// <param name="infoEntorno">Initial value of the infoEntorno property.</param>
        /// <param name="desuso">Initial value of the desuso property.</param>
        public static Entorno CreateEntorno(global::System.Int32 idEntorno, global::System.String infoEntorno, global::System.Int32 desuso)
        {
            Entorno entorno = new Entorno();
            entorno.idEntorno = idEntorno;
            entorno.infoEntorno = infoEntorno;
            entorno.desuso = desuso;
            return entorno;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEntorno
        {
            get
            {
                return _idEntorno;
            }
            set
            {
                if (_idEntorno != value)
                {
                    OnidEntornoChanging(value);
                    ReportPropertyChanging("idEntorno");
                    _idEntorno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEntorno");
                    OnidEntornoChanged();
                }
            }
        }
        private global::System.Int32 _idEntorno;
        partial void OnidEntornoChanging(global::System.Int32 value);
        partial void OnidEntornoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String infoEntorno
        {
            get
            {
                return _infoEntorno;
            }
            set
            {
                OninfoEntornoChanging(value);
                ReportPropertyChanging("infoEntorno");
                _infoEntorno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("infoEntorno");
                OninfoEntornoChanged();
            }
        }
        private global::System.String _infoEntorno;
        partial void OninfoEntornoChanging(global::System.String value);
        partial void OninfoEntornoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 desuso
        {
            get
            {
                return _desuso;
            }
            set
            {
                OndesusoChanging(value);
                ReportPropertyChanging("desuso");
                _desuso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("desuso");
                OndesusoChanged();
            }
        }
        private global::System.Int32 _desuso;
        partial void OndesusoChanging(global::System.Int32 value);
        partial void OndesusoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_Reporte_Entorno", "Reporte")]
        public EntityCollection<Reporte> Reporte
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reporte>("ReporteDBModel.FK_Reporte_Entorno", "Reporte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reporte>("ReporteDBModel.FK_Reporte_Entorno", "Reporte", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ReporteSolucionado_Entorno", "ReporteSolucionado")]
        public EntityCollection<ReporteSolucionado> ReporteSolucionado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReporteSolucionado>("ReporteDBModel.FK_ReporteSolucionado_Entorno", "ReporteSolucionado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReporteSolucionado>("ReporteDBModel.FK_ReporteSolucionado_Entorno", "ReporteSolucionado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="Equipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Equipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Equipo object.
        /// </summary>
        /// <param name="idEquipo">Initial value of the idEquipo property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="desuso">Initial value of the desuso property.</param>
        public static Equipo CreateEquipo(global::System.Int32 idEquipo, global::System.String nombre, global::System.Int32 desuso)
        {
            Equipo equipo = new Equipo();
            equipo.idEquipo = idEquipo;
            equipo.nombre = nombre;
            equipo.desuso = desuso;
            return equipo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEquipo
        {
            get
            {
                return _idEquipo;
            }
            set
            {
                if (_idEquipo != value)
                {
                    OnidEquipoChanging(value);
                    ReportPropertyChanging("idEquipo");
                    _idEquipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEquipo");
                    OnidEquipoChanged();
                }
            }
        }
        private global::System.Int32 _idEquipo;
        partial void OnidEquipoChanging(global::System.Int32 value);
        partial void OnidEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 desuso
        {
            get
            {
                return _desuso;
            }
            set
            {
                OndesusoChanging(value);
                ReportPropertyChanging("desuso");
                _desuso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("desuso");
                OndesusoChanged();
            }
        }
        private global::System.Int32 _desuso;
        partial void OndesusoChanging(global::System.Int32 value);
        partial void OndesusoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ProblemaPosible_Equipo1", "ProblemaPosible")]
        public EntityCollection<ProblemaPosible> ProblemaPosible
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProblemaPosible>("ReporteDBModel.FK_ProblemaPosible_Equipo1", "ProblemaPosible");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProblemaPosible>("ReporteDBModel.FK_ProblemaPosible_Equipo1", "ProblemaPosible", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_Reporte_Equipo", "Reporte")]
        public EntityCollection<Reporte> Reporte
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reporte>("ReporteDBModel.FK_Reporte_Equipo", "Reporte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reporte>("ReporteDBModel.FK_Reporte_Equipo", "Reporte", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ReporteSolucionado_Equipo", "ReporteSolucionado")]
        public EntityCollection<ReporteSolucionado> ReporteSolucionado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReporteSolucionado>("ReporteDBModel.FK_ReporteSolucionado_Equipo", "ReporteSolucionado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReporteSolucionado>("ReporteDBModel.FK_ReporteSolucionado_Equipo", "ReporteSolucionado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="ProblemaPosible")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProblemaPosible : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProblemaPosible object.
        /// </summary>
        /// <param name="idProblemaPosible">Initial value of the idProblemaPosible property.</param>
        /// <param name="idEquipo">Initial value of the idEquipo property.</param>
        /// <param name="problemaInfo">Initial value of the problemaInfo property.</param>
        /// <param name="desuso">Initial value of the desuso property.</param>
        public static ProblemaPosible CreateProblemaPosible(global::System.Int32 idProblemaPosible, global::System.Int32 idEquipo, global::System.String problemaInfo, global::System.Int32 desuso)
        {
            ProblemaPosible problemaPosible = new ProblemaPosible();
            problemaPosible.idProblemaPosible = idProblemaPosible;
            problemaPosible.idEquipo = idEquipo;
            problemaPosible.problemaInfo = problemaInfo;
            problemaPosible.desuso = desuso;
            return problemaPosible;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProblemaPosible
        {
            get
            {
                return _idProblemaPosible;
            }
            set
            {
                if (_idProblemaPosible != value)
                {
                    OnidProblemaPosibleChanging(value);
                    ReportPropertyChanging("idProblemaPosible");
                    _idProblemaPosible = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idProblemaPosible");
                    OnidProblemaPosibleChanged();
                }
            }
        }
        private global::System.Int32 _idProblemaPosible;
        partial void OnidProblemaPosibleChanging(global::System.Int32 value);
        partial void OnidProblemaPosibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEquipo
        {
            get
            {
                return _idEquipo;
            }
            set
            {
                OnidEquipoChanging(value);
                ReportPropertyChanging("idEquipo");
                _idEquipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idEquipo");
                OnidEquipoChanged();
            }
        }
        private global::System.Int32 _idEquipo;
        partial void OnidEquipoChanging(global::System.Int32 value);
        partial void OnidEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String problemaInfo
        {
            get
            {
                return _problemaInfo;
            }
            set
            {
                OnproblemaInfoChanging(value);
                ReportPropertyChanging("problemaInfo");
                _problemaInfo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("problemaInfo");
                OnproblemaInfoChanged();
            }
        }
        private global::System.String _problemaInfo;
        partial void OnproblemaInfoChanging(global::System.String value);
        partial void OnproblemaInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 desuso
        {
            get
            {
                return _desuso;
            }
            set
            {
                OndesusoChanging(value);
                ReportPropertyChanging("desuso");
                _desuso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("desuso");
                OndesusoChanged();
            }
        }
        private global::System.Int32 _desuso;
        partial void OndesusoChanging(global::System.Int32 value);
        partial void OndesusoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> consumible
        {
            get
            {
                return _consumible;
            }
            set
            {
                OnconsumibleChanging(value);
                ReportPropertyChanging("consumible");
                _consumible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("consumible");
                OnconsumibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _consumible;
        partial void OnconsumibleChanging(Nullable<global::System.Boolean> value);
        partial void OnconsumibleChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ProblemaPosible_Equipo1", "Equipo")]
        public Equipo Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_ProblemaPosible_Equipo1", "Equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_ProblemaPosible_Equipo1", "Equipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipo> EquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_ProblemaPosible_Equipo1", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipo>("ReporteDBModel.FK_ProblemaPosible_Equipo1", "Equipo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_Reporte_ProblemaPosible", "Reporte")]
        public EntityCollection<Reporte> Reporte
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reporte>("ReporteDBModel.FK_Reporte_ProblemaPosible", "Reporte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reporte>("ReporteDBModel.FK_Reporte_ProblemaPosible", "Reporte", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ReporteSolucionado_ProblemaPosible", "ReporteSolucionado")]
        public EntityCollection<ReporteSolucionado> ReporteSolucionado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReporteSolucionado>("ReporteDBModel.FK_ReporteSolucionado_ProblemaPosible", "ReporteSolucionado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReporteSolucionado>("ReporteDBModel.FK_ReporteSolucionado_ProblemaPosible", "ReporteSolucionado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="Reporte")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reporte : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reporte object.
        /// </summary>
        /// <param name="idReporte">Initial value of the idReporte property.</param>
        /// <param name="idEquipo">Initial value of the idEquipo property.</param>
        /// <param name="idProblemaPosible">Initial value of the idProblemaPosible property.</param>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="fecha_hora">Initial value of the fecha_hora property.</param>
        /// <param name="nombreCliente">Initial value of the nombreCliente property.</param>
        /// <param name="departamento">Initial value of the departamento property.</param>
        /// <param name="estado">Initial value of the estado property.</param>
        public static Reporte CreateReporte(global::System.Int32 idReporte, global::System.Int32 idEquipo, global::System.Int32 idProblemaPosible, global::System.String numero, global::System.DateTime fecha_hora, global::System.String nombreCliente, global::System.String departamento, global::System.String estado)
        {
            Reporte reporte = new Reporte();
            reporte.idReporte = idReporte;
            reporte.idEquipo = idEquipo;
            reporte.idProblemaPosible = idProblemaPosible;
            reporte.numero = numero;
            reporte.fecha_hora = fecha_hora;
            reporte.nombreCliente = nombreCliente;
            reporte.departamento = departamento;
            reporte.estado = estado;
            return reporte;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idReporte
        {
            get
            {
                return _idReporte;
            }
            set
            {
                if (_idReporte != value)
                {
                    OnidReporteChanging(value);
                    ReportPropertyChanging("idReporte");
                    _idReporte = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idReporte");
                    OnidReporteChanged();
                }
            }
        }
        private global::System.Int32 _idReporte;
        partial void OnidReporteChanging(global::System.Int32 value);
        partial void OnidReporteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idEntorno
        {
            get
            {
                return _idEntorno;
            }
            set
            {
                OnidEntornoChanging(value);
                ReportPropertyChanging("idEntorno");
                _idEntorno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idEntorno");
                OnidEntornoChanged();
            }
        }
        private Nullable<global::System.Int32> _idEntorno;
        partial void OnidEntornoChanging(Nullable<global::System.Int32> value);
        partial void OnidEntornoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEquipo
        {
            get
            {
                return _idEquipo;
            }
            set
            {
                OnidEquipoChanging(value);
                ReportPropertyChanging("idEquipo");
                _idEquipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idEquipo");
                OnidEquipoChanged();
            }
        }
        private global::System.Int32 _idEquipo;
        partial void OnidEquipoChanging(global::System.Int32 value);
        partial void OnidEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProblemaPosible
        {
            get
            {
                return _idProblemaPosible;
            }
            set
            {
                OnidProblemaPosibleChanging(value);
                ReportPropertyChanging("idProblemaPosible");
                _idProblemaPosible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idProblemaPosible");
                OnidProblemaPosibleChanged();
            }
        }
        private global::System.Int32 _idProblemaPosible;
        partial void OnidProblemaPosibleChanging(global::System.Int32 value);
        partial void OnidProblemaPosibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idAdministradorDefectando
        {
            get
            {
                return _idAdministradorDefectando;
            }
            set
            {
                OnidAdministradorDefectandoChanging(value);
                ReportPropertyChanging("idAdministradorDefectando");
                _idAdministradorDefectando = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idAdministradorDefectando");
                OnidAdministradorDefectandoChanged();
            }
        }
        private Nullable<global::System.Int32> _idAdministradorDefectando;
        partial void OnidAdministradorDefectandoChanging(Nullable<global::System.Int32> value);
        partial void OnidAdministradorDefectandoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.String _numero;
        partial void OnnumeroChanging(global::System.String value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_hora
        {
            get
            {
                return _fecha_hora;
            }
            set
            {
                Onfecha_horaChanging(value);
                ReportPropertyChanging("fecha_hora");
                _fecha_hora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_hora");
                Onfecha_horaChanged();
            }
        }
        private global::System.DateTime _fecha_hora;
        partial void Onfecha_horaChanging(global::System.DateTime value);
        partial void Onfecha_horaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String observacion
        {
            get
            {
                return _observacion;
            }
            set
            {
                OnobservacionChanging(value);
                ReportPropertyChanging("observacion");
                _observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("observacion");
                OnobservacionChanged();
            }
        }
        private global::System.String _observacion;
        partial void OnobservacionChanging(global::System.String value);
        partial void OnobservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreCliente
        {
            get
            {
                return _nombreCliente;
            }
            set
            {
                OnnombreClienteChanging(value);
                ReportPropertyChanging("nombreCliente");
                _nombreCliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreCliente");
                OnnombreClienteChanged();
            }
        }
        private global::System.String _nombreCliente;
        partial void OnnombreClienteChanging(global::System.String value);
        partial void OnnombreClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String departamento
        {
            get
            {
                return _departamento;
            }
            set
            {
                OndepartamentoChanging(value);
                ReportPropertyChanging("departamento");
                _departamento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("departamento");
                OndepartamentoChanged();
            }
        }
        private global::System.String _departamento;
        partial void OndepartamentoChanging(global::System.String value);
        partial void OndepartamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombrePC
        {
            get
            {
                return _nombrePC;
            }
            set
            {
                OnnombrePCChanging(value);
                ReportPropertyChanging("nombrePC");
                _nombrePC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombrePC");
                OnnombrePCChanged();
            }
        }
        private global::System.String _nombrePC;
        partial void OnnombrePCChanging(global::System.String value);
        partial void OnnombrePCChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_Reporte_Administrador", "Administrador")]
        public Administrador Administrador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Administrador>("ReporteDBModel.FK_Reporte_Administrador", "Administrador").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Administrador>("ReporteDBModel.FK_Reporte_Administrador", "Administrador").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Administrador> AdministradorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Administrador>("ReporteDBModel.FK_Reporte_Administrador", "Administrador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Administrador>("ReporteDBModel.FK_Reporte_Administrador", "Administrador", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_Reporte_Entorno", "Entorno")]
        public Entorno Entorno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entorno>("ReporteDBModel.FK_Reporte_Entorno", "Entorno").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entorno>("ReporteDBModel.FK_Reporte_Entorno", "Entorno").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Entorno> EntornoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entorno>("ReporteDBModel.FK_Reporte_Entorno", "Entorno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Entorno>("ReporteDBModel.FK_Reporte_Entorno", "Entorno", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_Reporte_Equipo", "Equipo")]
        public Equipo Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_Reporte_Equipo", "Equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_Reporte_Equipo", "Equipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipo> EquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_Reporte_Equipo", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipo>("ReporteDBModel.FK_Reporte_Equipo", "Equipo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_Reporte_ProblemaPosible", "ProblemaPosible")]
        public ProblemaPosible ProblemaPosible
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemaPosible>("ReporteDBModel.FK_Reporte_ProblemaPosible", "ProblemaPosible").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemaPosible>("ReporteDBModel.FK_Reporte_ProblemaPosible", "ProblemaPosible").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProblemaPosible> ProblemaPosibleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemaPosible>("ReporteDBModel.FK_Reporte_ProblemaPosible", "ProblemaPosible");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProblemaPosible>("ReporteDBModel.FK_Reporte_ProblemaPosible", "ProblemaPosible", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="ReporteSolucionado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReporteSolucionado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReporteSolucionado object.
        /// </summary>
        /// <param name="idReporteSolucionado">Initial value of the idReporteSolucionado property.</param>
        /// <param name="idEquipo">Initial value of the idEquipo property.</param>
        /// <param name="idProblemaPosible">Initial value of the idProblemaPosible property.</param>
        /// <param name="idAdministradorDefecto">Initial value of the idAdministradorDefecto property.</param>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="fecha_hora">Initial value of the fecha_hora property.</param>
        /// <param name="fecha_horaFin">Initial value of the fecha_horaFin property.</param>
        /// <param name="nombreCliente">Initial value of the nombreCliente property.</param>
        /// <param name="departamento">Initial value of the departamento property.</param>
        /// <param name="solucion">Initial value of the solucion property.</param>
        public static ReporteSolucionado CreateReporteSolucionado(global::System.Int32 idReporteSolucionado, global::System.Int32 idEquipo, global::System.Int32 idProblemaPosible, global::System.Int32 idAdministradorDefecto, global::System.String numero, global::System.DateTime fecha_hora, global::System.DateTime fecha_horaFin, global::System.String nombreCliente, global::System.String departamento, global::System.String solucion)
        {
            ReporteSolucionado reporteSolucionado = new ReporteSolucionado();
            reporteSolucionado.idReporteSolucionado = idReporteSolucionado;
            reporteSolucionado.idEquipo = idEquipo;
            reporteSolucionado.idProblemaPosible = idProblemaPosible;
            reporteSolucionado.idAdministradorDefecto = idAdministradorDefecto;
            reporteSolucionado.numero = numero;
            reporteSolucionado.fecha_hora = fecha_hora;
            reporteSolucionado.fecha_horaFin = fecha_horaFin;
            reporteSolucionado.nombreCliente = nombreCliente;
            reporteSolucionado.departamento = departamento;
            reporteSolucionado.solucion = solucion;
            return reporteSolucionado;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idReporteSolucionado
        {
            get
            {
                return _idReporteSolucionado;
            }
            set
            {
                if (_idReporteSolucionado != value)
                {
                    OnidReporteSolucionadoChanging(value);
                    ReportPropertyChanging("idReporteSolucionado");
                    _idReporteSolucionado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idReporteSolucionado");
                    OnidReporteSolucionadoChanged();
                }
            }
        }
        private global::System.Int32 _idReporteSolucionado;
        partial void OnidReporteSolucionadoChanging(global::System.Int32 value);
        partial void OnidReporteSolucionadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idEntorno
        {
            get
            {
                return _idEntorno;
            }
            set
            {
                OnidEntornoChanging(value);
                ReportPropertyChanging("idEntorno");
                _idEntorno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idEntorno");
                OnidEntornoChanged();
            }
        }
        private Nullable<global::System.Int32> _idEntorno;
        partial void OnidEntornoChanging(Nullable<global::System.Int32> value);
        partial void OnidEntornoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEquipo
        {
            get
            {
                return _idEquipo;
            }
            set
            {
                OnidEquipoChanging(value);
                ReportPropertyChanging("idEquipo");
                _idEquipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idEquipo");
                OnidEquipoChanged();
            }
        }
        private global::System.Int32 _idEquipo;
        partial void OnidEquipoChanging(global::System.Int32 value);
        partial void OnidEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProblemaPosible
        {
            get
            {
                return _idProblemaPosible;
            }
            set
            {
                OnidProblemaPosibleChanging(value);
                ReportPropertyChanging("idProblemaPosible");
                _idProblemaPosible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idProblemaPosible");
                OnidProblemaPosibleChanged();
            }
        }
        private global::System.Int32 _idProblemaPosible;
        partial void OnidProblemaPosibleChanging(global::System.Int32 value);
        partial void OnidProblemaPosibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAdministradorDefecto
        {
            get
            {
                return _idAdministradorDefecto;
            }
            set
            {
                OnidAdministradorDefectoChanging(value);
                ReportPropertyChanging("idAdministradorDefecto");
                _idAdministradorDefecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idAdministradorDefecto");
                OnidAdministradorDefectoChanged();
            }
        }
        private global::System.Int32 _idAdministradorDefecto;
        partial void OnidAdministradorDefectoChanging(global::System.Int32 value);
        partial void OnidAdministradorDefectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.String _numero;
        partial void OnnumeroChanging(global::System.String value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_hora
        {
            get
            {
                return _fecha_hora;
            }
            set
            {
                Onfecha_horaChanging(value);
                ReportPropertyChanging("fecha_hora");
                _fecha_hora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_hora");
                Onfecha_horaChanged();
            }
        }
        private global::System.DateTime _fecha_hora;
        partial void Onfecha_horaChanging(global::System.DateTime value);
        partial void Onfecha_horaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_horaFin
        {
            get
            {
                return _fecha_horaFin;
            }
            set
            {
                Onfecha_horaFinChanging(value);
                ReportPropertyChanging("fecha_horaFin");
                _fecha_horaFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_horaFin");
                Onfecha_horaFinChanged();
            }
        }
        private global::System.DateTime _fecha_horaFin;
        partial void Onfecha_horaFinChanging(global::System.DateTime value);
        partial void Onfecha_horaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String observacion
        {
            get
            {
                return _observacion;
            }
            set
            {
                OnobservacionChanging(value);
                ReportPropertyChanging("observacion");
                _observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("observacion");
                OnobservacionChanged();
            }
        }
        private global::System.String _observacion;
        partial void OnobservacionChanging(global::System.String value);
        partial void OnobservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreCliente
        {
            get
            {
                return _nombreCliente;
            }
            set
            {
                OnnombreClienteChanging(value);
                ReportPropertyChanging("nombreCliente");
                _nombreCliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreCliente");
                OnnombreClienteChanged();
            }
        }
        private global::System.String _nombreCliente;
        partial void OnnombreClienteChanging(global::System.String value);
        partial void OnnombreClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String departamento
        {
            get
            {
                return _departamento;
            }
            set
            {
                OndepartamentoChanging(value);
                ReportPropertyChanging("departamento");
                _departamento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("departamento");
                OndepartamentoChanged();
            }
        }
        private global::System.String _departamento;
        partial void OndepartamentoChanging(global::System.String value);
        partial void OndepartamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String solucion
        {
            get
            {
                return _solucion;
            }
            set
            {
                OnsolucionChanging(value);
                ReportPropertyChanging("solucion");
                _solucion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("solucion");
                OnsolucionChanged();
            }
        }
        private global::System.String _solucion;
        partial void OnsolucionChanging(global::System.String value);
        partial void OnsolucionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombrePC
        {
            get
            {
                return _nombrePC;
            }
            set
            {
                OnnombrePCChanging(value);
                ReportPropertyChanging("nombrePC");
                _nombrePC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombrePC");
                OnnombrePCChanged();
            }
        }
        private global::System.String _nombrePC;
        partial void OnnombrePCChanging(global::System.String value);
        partial void OnnombrePCChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ReporteSolucionado_Administrador", "Administrador")]
        public Administrador Administrador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Administrador>("ReporteDBModel.FK_ReporteSolucionado_Administrador", "Administrador").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Administrador>("ReporteDBModel.FK_ReporteSolucionado_Administrador", "Administrador").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Administrador> AdministradorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Administrador>("ReporteDBModel.FK_ReporteSolucionado_Administrador", "Administrador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Administrador>("ReporteDBModel.FK_ReporteSolucionado_Administrador", "Administrador", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ReporteSolucionado_Entorno", "Entorno")]
        public Entorno Entorno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entorno>("ReporteDBModel.FK_ReporteSolucionado_Entorno", "Entorno").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entorno>("ReporteDBModel.FK_ReporteSolucionado_Entorno", "Entorno").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Entorno> EntornoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entorno>("ReporteDBModel.FK_ReporteSolucionado_Entorno", "Entorno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Entorno>("ReporteDBModel.FK_ReporteSolucionado_Entorno", "Entorno", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ReporteSolucionado_Equipo", "Equipo")]
        public Equipo Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_ReporteSolucionado_Equipo", "Equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_ReporteSolucionado_Equipo", "Equipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipo> EquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("ReporteDBModel.FK_ReporteSolucionado_Equipo", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipo>("ReporteDBModel.FK_ReporteSolucionado_Equipo", "Equipo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReporteDBModel", "FK_ReporteSolucionado_ProblemaPosible", "ProblemaPosible")]
        public ProblemaPosible ProblemaPosible
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemaPosible>("ReporteDBModel.FK_ReporteSolucionado_ProblemaPosible", "ProblemaPosible").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemaPosible>("ReporteDBModel.FK_ReporteSolucionado_ProblemaPosible", "ProblemaPosible").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProblemaPosible> ProblemaPosibleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProblemaPosible>("ReporteDBModel.FK_ReporteSolucionado_ProblemaPosible", "ProblemaPosible");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProblemaPosible>("ReporteDBModel.FK_ReporteSolucionado_ProblemaPosible", "ProblemaPosible", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReporteDBModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
