//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReporteDBEntities : DbContext
    {
        public ReporteDBEntities()
            : base("name=ReporteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Acceso> Acceso { get; set; }
        public DbSet<Administrador> Administrador { get; set; }
        public DbSet<Consecutivo> Consecutivo { get; set; }
        public DbSet<Entorno> Entorno { get; set; }
        public DbSet<Equipo> Equipo { get; set; }
        public DbSet<ProblemaPosible> ProblemaPosible { get; set; }
        public DbSet<Reporte> Reporte { get; set; }
        public DbSet<ReporteSolucionado> ReporteSolucionado { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
